service: truenorth-calculator-backend
useDotenv: true

app: truenorth-calculator-backend
org: javierfvasquezr

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: go1.x
  httpApi:
    cors: true
  environment:
    MONGO_URI: ${env:MONGO_URI}
    DB_NAME: ${env:DB_NAME}

package:
  patterns:
    - "!./**"
    - ./bin/**
    - "!./bin/v1/*.zip"

functions:
  addition:
    handler: bin/v1/addition
    events:
      - httpApi:
          path: /addition
          method: post
  substraction:
    handler: bin/v1/substraction
    events:
      - httpApi:
          path: /substraction
          method: post
  multiplication:
    handler: bin/v1/multiplication
    events:
      - httpApi:
          path: /multiplication
          method: post
  division:
    handler: bin/v1/division
    events:
      - httpApi:
          path: /division
          method: post
  squareRoot:
    handler: bin/v1/squareRoot
    events:
      - httpApi:
          path: /squareRoot
          method: post
  randomString:
    handler: bin/v1/randomString
    events:
      - httpApi:
          path: /randomString
          method: post
  recordList:
    handler: bin/v1/recordList
    events:
      - httpApi:
          path: /record
          method: get
  getBalance:
    handler: bin/v1/getBalance
    events:
      - httpApi:
          path: /balance
          method: get
