AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  addition:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/addition
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /addition
            Method: post
            Cors:
              AllowMethods: "'GET, POST, PUT'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  substraction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/substraction
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /substraction
            Method: post
            Cors:
              AllowMethods: "'GET, POST, PUT'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  multiplication:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/multiplication
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /multiplication
            Method: post
            Cors:
              AllowMethods: "'GET, POST, PUT'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  division:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/division
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /division
            Method: post
            Cors:
              AllowMethods: "'GET, POST, PUT'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  squareRoot:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/squareRoot
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /squareRoot
            Method: post
            Cors:
              AllowMethods: "'GET, POST, PUT'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  randomString:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/randomString
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /randomString
            Method: post
            Cors:
              AllowMethods: "'GET, POST, PUT'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  recordList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/recordList
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /record
            Method: get
            Cors:
              AllowMethods: "'GET, POST, PUT'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
