AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  addition:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/addition
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /addition
            Method: post
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  substraction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/substraction
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /substraction
            Method: post
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  multiplication:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/multiplication
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /multiplication
            Method: post
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  division:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/division
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /division
            Method: post
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  squareRoot:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/squareRoot
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /squareRoot
            Method: post
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  randomString:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/randomString
      Runtime: go1.x
      Timeout: 60
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /randomString
            Method: post
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  recordList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/recordList
      Runtime: go1.x
      Timeout: 60
      Events:
        Options:
          Type: Api
          Properties:
            Path: /{cors+}
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /record
            Method: get
            Cors:
              AllowMethods: "'GET'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
              AllowCredentials: false
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  deleteRecord:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/deleteRecord
      Runtime: go1.x
      Timeout: 60
      Events:
        Options:
          Type: Api
          Properties:
            Path: /{cors+}
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /record/{id}
            Method: delete
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
  getBalance:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bin/v1/getBalance
      Runtime: go1.x
      Timeout: 60
      Events:
        Options:
          Type: Api
          Properties:
            Path: /{cors+}
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /balance
            Method: get
      Environment:
        Variables:
          MONGO_URI: mongodb+srv://javierfvasquezr:OPSysYjLRg6drbha@truenorth.yeghafr.mongodb.net/?retryWrites=true&w=majority
          DB_NAME: truenorth
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
      AllowOrigin: "'*'"
