// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRandomStringRepositoryIF is an autogenerated mock type for the RandomStringRepositoryIF type
type MockRandomStringRepositoryIF struct {
	mock.Mock
}

type MockRandomStringRepositoryIF_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRandomStringRepositoryIF) EXPECT() *MockRandomStringRepositoryIF_Expecter {
	return &MockRandomStringRepositoryIF_Expecter{mock: &_m.Mock}
}

// GetRandomString provides a mock function with given fields: ctx
func (_m *MockRandomStringRepositoryIF) GetRandomString(ctx context.Context) (*string, error) {
	ret := _m.Called(ctx)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRandomStringRepositoryIF_GetRandomString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomString'
type MockRandomStringRepositoryIF_GetRandomString_Call struct {
	*mock.Call
}

// GetRandomString is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRandomStringRepositoryIF_Expecter) GetRandomString(ctx interface{}) *MockRandomStringRepositoryIF_GetRandomString_Call {
	return &MockRandomStringRepositoryIF_GetRandomString_Call{Call: _e.mock.On("GetRandomString", ctx)}
}

func (_c *MockRandomStringRepositoryIF_GetRandomString_Call) Run(run func(ctx context.Context)) *MockRandomStringRepositoryIF_GetRandomString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRandomStringRepositoryIF_GetRandomString_Call) Return(_a0 *string, _a1 error) *MockRandomStringRepositoryIF_GetRandomString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRandomStringRepositoryIF_GetRandomString_Call) RunAndReturn(run func(context.Context) (*string, error)) *MockRandomStringRepositoryIF_GetRandomString_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRandomStringRepositoryIF interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRandomStringRepositoryIF creates a new instance of MockRandomStringRepositoryIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRandomStringRepositoryIF(t mockConstructorTestingTNewMockRandomStringRepositoryIF) *MockRandomStringRepositoryIF {
	mock := &MockRandomStringRepositoryIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
