// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/JavierFVasquez/golang-calculator-backend/libs/models"
	mock "github.com/stretchr/testify/mock"
)

// MockRandomStringServiceIF is an autogenerated mock type for the RandomStringServiceIF type
type MockRandomStringServiceIF struct {
	mock.Mock
}

type MockRandomStringServiceIF_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRandomStringServiceIF) EXPECT() *MockRandomStringServiceIF_Expecter {
	return &MockRandomStringServiceIF_Expecter{mock: &_m.Mock}
}

// RandomString provides a mock function with given fields: ctx, operation
func (_m *MockRandomStringServiceIF) RandomString(ctx context.Context, operation models.Operation) (*models.Record, *error) {
	ret := _m.Called(ctx, operation)

	var r0 *models.Record
	var r1 *error
	if rf, ok := ret.Get(0).(func(context.Context, models.Operation) (*models.Record, *error)); ok {
		return rf(ctx, operation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Operation) *models.Record); ok {
		r0 = rf(ctx, operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Operation) *error); ok {
		r1 = rf(ctx, operation)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*error)
		}
	}

	return r0, r1
}

// MockRandomStringServiceIF_RandomString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RandomString'
type MockRandomStringServiceIF_RandomString_Call struct {
	*mock.Call
}

// RandomString is a helper method to define mock.On call
//   - ctx context.Context
//   - operation models.Operation
func (_e *MockRandomStringServiceIF_Expecter) RandomString(ctx interface{}, operation interface{}) *MockRandomStringServiceIF_RandomString_Call {
	return &MockRandomStringServiceIF_RandomString_Call{Call: _e.mock.On("RandomString", ctx, operation)}
}

func (_c *MockRandomStringServiceIF_RandomString_Call) Run(run func(ctx context.Context, operation models.Operation)) *MockRandomStringServiceIF_RandomString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Operation))
	})
	return _c
}

func (_c *MockRandomStringServiceIF_RandomString_Call) Return(_a0 *models.Record, _a1 *error) *MockRandomStringServiceIF_RandomString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRandomStringServiceIF_RandomString_Call) RunAndReturn(run func(context.Context, models.Operation) (*models.Record, *error)) *MockRandomStringServiceIF_RandomString_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRandomStringServiceIF interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRandomStringServiceIF creates a new instance of MockRandomStringServiceIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRandomStringServiceIF(t mockConstructorTestingTNewMockRandomStringServiceIF) *MockRandomStringServiceIF {
	mock := &MockRandomStringServiceIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
